<?php

namespace ContainerWvgaxZH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInnerUploaderService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Service\InnerUploader' shared autowired service.
     *
     * @return \App\Service\InnerUploader
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/AbstractUploader.php';
        include_once \dirname(__DIR__, 4).'/src/Service/InnerUploader.php';

        return $container->privates['App\\Service\\InnerUploader'] = new \App\Service\InnerUploader(($container->privates['parameter_bag'] ?? ($container->privates['parameter_bag'] = new \Symfony\Component\DependencyInjection\ParameterBag\ContainerBag($container))));
    }
}
