<?php

namespace ContainerWBwjBgu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRemoveImgCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\RemoveImgCommand' shared autowired service.
     *
     * @return \App\Command\RemoveImgCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/RemoveImgCommand.php';

        $container->privates['App\\Command\\RemoveImgCommand'] = $instance = new \App\Command\RemoveImgCommand(($container->privates['App\\Helper\\FileHelper'] ?? $container->load('getFileHelperService')), ($container->privates['parameter_bag'] ?? ($container->privates['parameter_bag'] = new \Symfony\Component\DependencyInjection\ParameterBag\ContainerBag($container))));

        $instance->setName('app:remove-img');
        $instance->setDescription('Add a short description for your command');

        return $instance;
    }
}
