<?php

namespace ContainerWBwjBgu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUploadImgCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\UploadImgCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Command\\UploadImgCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:upload-img', [], 'CLI app for uploading images', false, function () use ($container): \App\Command\UploadImgCommand {
            return ($container->privates['App\\Command\\UploadImgCommand'] ?? $container->load('getUploadImgCommandService'));
        });
    }
}
