<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWvgaxZH\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWvgaxZH/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerWvgaxZH.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerWvgaxZH\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerWvgaxZH\App_KernelTestDebugContainer([
    'container.build_hash' => 'WvgaxZH',
    'container.build_id' => 'e324352e',
    'container.build_time' => 1649163523,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWvgaxZH');
