<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWBwjBgu\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWBwjBgu/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWBwjBgu.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWBwjBgu\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWBwjBgu\App_KernelDevDebugContainer([
    'container.build_hash' => 'WBwjBgu',
    'container.build_id' => '3d8e2b33',
    'container.build_time' => 1649156821,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWBwjBgu');
